version: '3.3'

services:
  novaops-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: novaops-backend
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    environment:
      NOVA_MQTT_BROKER: host.docker.internal
      NOVA_MQTT_PORT: "1883"
    environment:
      - PYTHONPATH=/app